apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello
  annotations:
    workflows.argoproj.io/description: |
      This is simple example from sosotech
spec:
  serviceAccountName: argo 
  entrypoint: main
  templates:
  - name: main
    container: 
      image: docker/whalesay
      command: ["cowsay"]

