apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: nodejs-ecr
  annotations:
    workflows.argoproj.io/description: |
      Pulling image from Aws-Ecr
spec:
  serviceAccountName: argo  # Ensure this matches the service account configured above
  entrypoint: main
  imagePullSecrets:
  - name: ecr-registry-secret-argo
  templates:
  - name: main
    container:
      image: 368085106192.dkr.ecr.us-east-1.amazonaws.com/sosotech:1.0.0
      command: ["/bin/sh"]
      args: ["-c", "echo Hello, Argo!"]
      # command: ["/bin/sh"]
      # args: ["-c", "echo Hello, Argo! && python -m http.server 8080"]
      ports:
        - containerPort: 80

