apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: helloer
  annotations:
    workflows.argoproj.io/description: |
      This is a simple example from sosotech
spec:
  serviceAccountName: argo 
  entrypoint: main
  templates:
  - name: main
    script:
      image: ubuntu:20.04  # Using Ubuntu base image
      command: [bash]
      source: |
        set -eo pipefail

        # Update package list and install prerequisites
        echo "Updating package list..."
        apt-get update -y

        # Install Python
        echo "Installing Python..."
        apt-get install -y python3 python3-pip

        # Install Git
        echo "Installing Git..."
        apt-get install -y git

        # Install AWS CLI
        echo "Installing AWS CLI..."
        apt-get install -y curl unzip
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        ./aws/install
        rm -rf awscliv2.zip aws

        # Verify installations
        echo "Verifying installations..."
        python3 --version
        pip3 --version
        git --version
        aws --version

      resources:
        requests:
          ephemeral-storage: "2Gi"
        limits:
          ephemeral-storage: "4Gi"

## add storage because error msg, node was running low on resources
## Container main was using 954184Ki, request is 0, has larger consumption of ephemeral-storage
