apiVersion: v1
kind: ConfigMap
metadata:
  name: install-script
  namespace: argo
data:
  install.sh: |
    #!/bin/bash
    set -eo pipefail

    # Update package list and install prerequisites
    echo "Updating package list..."
    apt-get update -y

    # Install Python
    echo "Installing Python..."
    apt-get install -y python3 python3-pip

    # Install Git
    echo "Installing Git..."
    apt-get install -y git

    # Install AWS CLI
    echo "Installing AWS CLI..."
    apt-get install -y curl unzip
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    ./aws/install

    # Verify installations
    echo "Verifying installations..."
    python3 --version
    pip3 --version
    git --version
    aws --version
