apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls
  namespace: keycloak
spec:
  dnsNames:
  - "*.re-lux.club"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: keycloak-tls
